siteweb_front_homepage:
    pattern:  /
    defaults: { _controller: SitewebFrontBundle:Default:index }

new_summit_registration:
    pattern:  /reg
    defaults: { _controller: SitewebFrontBundle:Default:summitregistration }

summit_abstracts:
    pattern:  /abstracts
    defaults: { _controller: SitewebFrontBundle:Abstract:abstract }

summit_abstract_submission:
    pattern:  /track/{id}/abstract/submission
    defaults: { _controller: SitewebFrontBundle:Abstract:abstractregister }


summit_paypal_payment:
    pattern:  /payment
    defaults: { _controller: SitewebFrontBundle:Payment:preparePaypalExpressCheckoutPayment }


summit_paypal_payment_done:
    pattern:  /payment/done
    defaults: { _controller: SitewebFrontBundle:Payment:captureDone }

summit_payment_renew:
    pattern:  /renew/payment
    defaults: { _controller: SitewebFrontBundle:RenewPayment:prepareRenewPayment }

summit_mission:
    pattern:  /mission
    defaults: { _controller: SitewebFrontBundle:Mission:mission }

summit_ourwork:
    pattern:  /our-work
    defaults: { _controller: SitewebFrontBundle:OurWork:ourwork }

summit_research_agenda:
    pattern:  /our-services
    defaults: { _controller: SitewebFrontBundle:ResearchAgenda:researchagenda }

summit_ourservices:
    pattern:  /our-services
    defaults: { _controller: SitewebFrontBundle:OurServices:ourservices }

summit_bgrg_summits:
    pattern:  /bgrg-summits
    defaults: { _controller: SitewebFrontBundle:BGRGSummits:bgrgsummits }

summit_annual_reports:
    pattern:  /annual-reports
    defaults: { _controller: SitewebFrontBundle:AnnualReports:annualreports }

summit_board_of_directors:
    pattern:  /board-of-directors
    defaults: { _controller: SitewebFrontBundle:BoardofDirectors:boardofdirectors }

summit_affiliate_members:
    pattern:  /affiliate-members
    defaults: { _controller: SitewebFrontBundle:AffiliateMembers:affiliatemembers }

summit_all_members:
    pattern:  /all-members
    defaults: { _controller: SitewebFrontBundle:AllMembers:allmembers }

summit_committees:
    pattern:  /committees
    defaults: { _controller: SitewebFrontBundle:Committees:committees }

summit_founding_members:
    pattern:  /founding_members
    defaults: { _controller: SitewebFrontBundle:FoundingMembers:foundingmembers }

summit_organizational_members:
    pattern:  /organizational_members
    defaults: { _controller: SitewebFrontBundle:OrganizationalMembers:organizationalmembers }

summit_advertise:
    pattern:  /advertise
    defaults: { _controller: SitewebFrontBundle:Advertise:advertise }

summit_donate:
    pattern:  /donate
    defaults: { _controller: SitewebFrontBundle:Donate:donate }

summit_volunteer:
    pattern:  /volunteer
    defaults: { _controller: SitewebFrontBundle:Volunteer:volunteer }

summit_job_opportunities:
    pattern:  /job-opportunities
    defaults: { _controller: SitewebFrontBundle:JobOpportunities:jobopportunities }