parameters:
#    siteweb_back.example.class: Siteweb\BackBundle\Example

services:
#    siteweb_back.example:
#        class: %siteweb_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
