parameters:
#    siteweb_front.example.class: Siteweb\FrontBundle\Example

services:
    siteweb_user.registration.form.type:
        class: Siteweb\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: siteweb_user_registration }


    siteweb_user.profile.form.type:
        class: Siteweb\UserBundle\Form\EditUserType
        tags:
            - { name: form.type, alias: siteweb_edit_user_registration }

    bgrg.payment.payum.action.store_notification:
        class: Siteweb\FrontBundle\Payum\Action\StoreNotificationAction
        arguments:
            - @doctrine
